version: "3"
services:
  app:
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: sam-graphql
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    tty: true
    command: tail -f /dev/null
    extra_hosts:
      - host.docker.internal:host-gateway
